// Supabase Database Type Definitions
// This file is automatically generated based on the Supabase schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// Enums
export type AppRole = 'ceo' | 'supervisor' | 'worker';
export type ApprovalStatus = 'pending' | 'approved' | 'rejected';
export type EmploymentType = 'permanent' | 'temporary';
export type TimesheetStatus = 'pending' | 'approved' | 'flagged' | 'rejected';
export type PayslipStatus = 'draft' | 'generated' | 'paid';
export type TransactionType = 'payroll' | 'expense' | 'reimbursement' | 'bonus' | 'deduction';

// Database Type
export type Database = {
  public: {
    Tables: {
      user_roles: {
        Row: {
          id: string;
          user_id: string;
          role: AppRole;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          role?: AppRole;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          role?: AppRole;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "user_roles_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          email: string | null;
          phone: string | null;
          position: string | null;
          department: string | null;
          employment_type: EmploymentType | null;
          supervisor_id: string | null;
          avatar_url: string | null;
          location: string | null;
          hourly_rate: number | null;
          base_salary: number | null;
          worker_type: EmploymentType | null;
          is_resident: boolean | null;
          super_enabled: boolean | null;
          account_status: ApprovalStatus | null;
          is_active: boolean | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          email?: string | null;
          phone?: string | null;
          position?: string | null;
          department?: string | null;
          employment_type?: EmploymentType | null;
          supervisor_id?: string | null;
          avatar_url?: string | null;
          location?: string | null;
          hourly_rate?: number | null;
          base_salary?: number | null;
          worker_type?: EmploymentType | null;
          is_resident?: boolean | null;
          super_enabled?: boolean | null;
          account_status?: ApprovalStatus | null;
          is_active?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string | null;
          email?: string | null;
          phone?: string | null;
          position?: string | null;
          department?: string | null;
          employment_type?: EmploymentType | null;
          supervisor_id?: string | null;
          avatar_url?: string | null;
          location?: string | null;
          hourly_rate?: number | null;
          base_salary?: number | null;
          worker_type?: EmploymentType | null;
          is_resident?: boolean | null;
          super_enabled?: boolean | null;
          account_status?: ApprovalStatus | null;
          is_active?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "profiles_supervisor_id_fkey";
            columns: ["supervisor_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "profiles_id_fkey";
            columns: ["id"];
            isOneToOne: true;
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
      bank_details: {
        Row: {
          id: string;
          user_id: string;
          bank_name: string | null;
          branch: string | null;
          account_name: string | null;
          account_number: string | null;
          bsb_code: string | null;
          swift_code: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          bank_name?: string | null;
          branch?: string | null;
          account_name?: string | null;
          account_number?: string | null;
          bsb_code?: string | null;
          swift_code?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          bank_name?: string | null;
          branch?: string | null;
          account_name?: string | null;
          account_number?: string | null;
          bsb_code?: string | null;
          swift_code?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "bank_details_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: true;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      contracts: {
        Row: {
          id: string;
          worker_id: string;
          start_date: string;
          end_date: string;
          daily_rate: number | null;
          hourly_rate: number | null;
          description: string | null;
          is_active: boolean | null;
          approved_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          worker_id: string;
          start_date: string;
          end_date: string;
          daily_rate?: number | null;
          hourly_rate?: number | null;
          description?: string | null;
          is_active?: boolean | null;
          approved_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          worker_id?: string;
          start_date?: string;
          end_date?: string;
          daily_rate?: number | null;
          hourly_rate?: number | null;
          description?: string | null;
          is_active?: boolean | null;
          approved_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "contracts_worker_id_fkey";
            columns: ["worker_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "contracts_approved_by_fkey";
            columns: ["approved_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      timesheets: {
        Row: {
          id: string;
          worker_id: string;
          supervisor_id: string;
          date: string;
          clock_in: string;
          clock_out: string;
          total_hours: number | null;
          task_description: string | null;
          status: TimesheetStatus | null;
          approved_by: string | null;
          approved_at: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          worker_id: string;
          supervisor_id: string;
          date: string;
          clock_in: string;
          clock_out: string;
          total_hours?: number | null;
          task_description?: string | null;
          status?: TimesheetStatus | null;
          approved_by?: string | null;
          approved_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          worker_id?: string;
          supervisor_id?: string;
          date?: string;
          clock_in?: string;
          clock_out?: string;
          total_hours?: number | null;
          task_description?: string | null;
          status?: TimesheetStatus | null;
          approved_by?: string | null;
          approved_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "timesheets_worker_id_fkey";
            columns: ["worker_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "timesheets_supervisor_id_fkey";
            columns: ["supervisor_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "timesheets_approved_by_fkey";
            columns: ["approved_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      payslips: {
        Row: {
          id: string;
          worker_id: string;
          period_start: string;
          period_end: string;
          total_hours: number | null;
          hourly_rate: number | null;
          gross_pay: number | null;
          deductions: number | null;
          net_pay: number | null;
          status: PayslipStatus | null;
          generated_by: string | null;
          paid_by: string | null;
          paid_at: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          worker_id: string;
          period_start: string;
          period_end: string;
          total_hours?: number | null;
          hourly_rate?: number | null;
          gross_pay?: number | null;
          deductions?: number | null;
          net_pay?: number | null;
          status?: PayslipStatus | null;
          generated_by?: string | null;
          paid_by?: string | null;
          paid_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          worker_id?: string;
          period_start?: string;
          period_end?: string;
          total_hours?: number | null;
          hourly_rate?: number | null;
          gross_pay?: number | null;
          deductions?: number | null;
          net_pay?: number | null;
          status?: PayslipStatus | null;
          generated_by?: string | null;
          paid_by?: string | null;
          paid_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "payslips_worker_id_fkey";
            columns: ["worker_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "payslips_generated_by_fkey";
            columns: ["generated_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "payslips_paid_by_fkey";
            columns: ["paid_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      messages: {
        Row: {
          id: string;
          sender_id: string;
          receiver_id: string | null;
          content: string;
          is_broadcast: boolean | null;
          broadcast_to_role: AppRole | null;
          is_system_message: boolean | null;
          read_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          sender_id: string;
          receiver_id?: string | null;
          content: string;
          is_broadcast?: boolean | null;
          broadcast_to_role?: AppRole | null;
          is_system_message?: boolean | null;
          read_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          sender_id?: string;
          receiver_id?: string | null;
          content?: string;
          is_broadcast?: boolean | null;
          broadcast_to_role?: AppRole | null;
          is_system_message?: boolean | null;
          read_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "messages_sender_id_fkey";
            columns: ["sender_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "messages_receiver_id_fkey";
            columns: ["receiver_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      financial_transactions: {
        Row: {
          id: string;
          transaction_type: TransactionType | null;
          amount: number | null;
          description: string | null;
          related_payslip_id: string | null;
          related_worker_id: string | null;
          recorded_by: string | null;
          category: string | null;
          reference_number: string | null;
          transaction_date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          transaction_type: TransactionType | null;
          amount?: number | null;
          description?: string | null;
          related_payslip_id?: string | null;
          related_worker_id?: string | null;
          recorded_by?: string | null;
          category?: string | null;
          reference_number?: string | null;
          transaction_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          transaction_type?: TransactionType | null;
          amount?: number | null;
          description?: string | null;
          related_payslip_id?: string | null;
          related_worker_id?: string | null;
          recorded_by?: string | null;
          category?: string | null;
          reference_number?: string | null;
          transaction_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "financial_transactions_related_payslip_id_fkey";
            columns: ["related_payslip_id"];
            isOneToOne: false;
            referencedRelation: "payslips";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "financial_transactions_related_worker_id_fkey";
            columns: ["related_worker_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "financial_transactions_recorded_by_fkey";
            columns: ["recorded_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      account_approvals: {
        Row: {
          id: string;
          user_id: string;
          requested_role: AppRole | null;
          status: ApprovalStatus | null;
          reviewed_by: string | null;
          reviewed_at: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          requested_role?: AppRole | null;
          status?: ApprovalStatus | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          requested_role?: AppRole | null;
          status?: ApprovalStatus | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "account_approvals_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "account_approvals_reviewed_by_fkey";
            columns: ["reviewed_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      attendance: {
        Row: {
          id: string;
          worker_id: string;
          clock_in: string | null;
          clock_out: string | null;
          status: string | null;
          approved_by: string | null;
          approved_at: string | null;
          notes: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          worker_id: string;
          clock_in?: string | null;
          clock_out?: string | null;
          status?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          notes?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          worker_id?: string;
          clock_in?: string | null;
          clock_out?: string | null;
          status?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          notes?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "attendance_worker_id_fkey";
            columns: ["worker_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "attendance_approved_by_fkey";
            columns: ["approved_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      payroll_entries: {
        Row: {
          id: string;
          worker_id: string | null;
          period_start: string | null;
          period_end: string | null;
          gross_pay: number | null;
          net_pay: number | null;
          super: number | null;
          tax: number | null;
          deductions: number | null;
          status: string | null;
          paid_at: string | null;
          paid_by: string | null;
          payslip_url: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          worker_id?: string | null;
          period_start?: string | null;
          period_end?: string | null;
          gross_pay?: number | null;
          net_pay?: number | null;
          super?: number | null;
          tax?: number | null;
          deductions?: number | null;
          status?: string | null;
          paid_at?: string | null;
          paid_by?: string | null;
          payslip_url?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          worker_id?: string | null;
          period_start?: string | null;
          period_end?: string | null;
          gross_pay?: number | null;
          net_pay?: number | null;
          super?: number | null;
          tax?: number | null;
          deductions?: number | null;
          status?: string | null;
          paid_at?: string | null;
          paid_by?: string | null;
          payslip_url?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "payroll_entries_worker_id_fkey";
            columns: ["worker_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "payroll_entries_paid_by_fkey";
            columns: ["paid_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      audit_log: {
        Row: {
          id: string;
          user_id: string | null;
          action: string | null;
          target_table: string | null;
          target_id: string | null;
          details: Json | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          action?: string | null;
          target_table?: string | null;
          target_id?: string | null;
          details?: Json | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          action?: string | null;
          target_table?: string | null;
          target_id?: string | null;
          details?: Json | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      work_summaries: {
        Row: {
          id: string;
          worker_id: string;
          period_start: string;
          period_end: string;
          summary: string;
          tasks_completed: string | null;
          challenges: string | null;
          next_period_goals: string | null;
          submitted_at: string | null;
          reviewed_by: string | null;
          reviewed_at: string | null;
          status: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          worker_id: string;
          period_start: string;
          period_end: string;
          summary: string;
          tasks_completed?: string | null;
          challenges?: string | null;
          next_period_goals?: string | null;
          submitted_at?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          status?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          worker_id?: string;
          period_start?: string;
          period_end?: string;
          summary?: string;
          tasks_completed?: string | null;
          challenges?: string | null;
          next_period_goals?: string | null;
          submitted_at?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          status?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "work_summaries_worker_id_fkey";
            columns: ["worker_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "work_summaries_reviewed_by_fkey";
            columns: ["reviewed_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      employees: {
        Row: {
          id: string;
          employee_number: string | null;
          full_name: string | null;
          email: string | null;
          phone: string | null;
          position: string | null;
          department: string | null;
          base_salary: number | null;
          is_resident: boolean | null;
          user_id: string | null;
          status: string | null;
          join_date: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          employee_number?: string | null;
          full_name?: string | null;
          email?: string | null;
          phone?: string | null;
          position?: string | null;
          department?: string | null;
          base_salary?: number | null;
          is_resident?: boolean | null;
          user_id?: string | null;
          status?: string | null;
          join_date?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          employee_number?: string | null;
          full_name?: string | null;
          email?: string | null;
          phone?: string | null;
          position?: string | null;
          department?: string | null;
          base_salary?: number | null;
          is_resident?: boolean | null;
          user_id?: string | null;
          status?: string | null;
          join_date?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      payroll_cycles: {
        Row: {
          id: string;
          period_start: string | null;
          period_end: string | null;
          status: string | null;
          run_by: string | null;
          approved_by: string | null;
          total_gross: number | null;
          total_paye: number | null;
          total_net: number | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          period_start?: string | null;
          period_end?: string | null;
          status?: string | null;
          run_by?: string | null;
          approved_by?: string | null;
          total_gross?: number | null;
          total_paye?: number | null;
          total_net?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          period_start?: string | null;
          period_end?: string | null;
          status?: string | null;
          run_by?: string | null;
          approved_by?: string | null;
          total_gross?: number | null;
          total_paye?: number | null;
          total_net?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      get_supervisor_id: {
        Args: {
          _user_id: string;
        };
        Returns: string;
      };
      has_role: {
        Args: {
          _user_id: string;
          _role: AppRole;
        };
        Returns: boolean;
      };
      is_accountant: {
        Args: {
          _user_id: string;
        };
        Returns: boolean;
      };
      is_admin: {
        Args: {
          _user_id: string;
        };
        Returns: boolean;
      };
      is_supervisor_of: {
        Args: {
          _supervisor_id: string;
          _worker_id: string;
        };
        Returns: boolean;
      };
    };
    Enums: {
      app_role: AppRole;
      approval_status: ApprovalStatus;
      employment_type: EmploymentType;
      payslip_status: PayslipStatus;
      timesheet_status: TimesheetStatus;
      transaction_type: TransactionType;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

// Helper types for table operations
export type Tables<T> = T extends keyof Database['public']['Tables']
  ? Database['public']['Tables'][T] extends { Row: infer R }
    ? R
    : never
  : never;

export type TablesInsert<T> = T extends keyof Database['public']['Tables']
  ? Database['public']['Tables'][T] extends { Insert: infer I }
    ? I
    : never
  : never;

export type TablesUpdate<T> = T extends keyof Database['public']['Tables']
  ? Database['public']['Tables'][T] extends { Update: infer U }
    ? U
    : never
  : never;
